[package]
name = "x52-spotify"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
xcb = "0.8"
signal-hook = "0.1.9"
crossbeam = "0.7.1"

[build-dependencies]
bindgen = "0.49.2"